name: Compile LaTeX

on:
  # Trigger the workflow on push, but only for the main branch
  push:
    branches:
      - main

jobs:
  compile-latex:
    name: Compile LaTeX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up GhostScript optimiser
        run: sudo apt-get install ghostscript

      - name: Get Go dependencies
        run: go get ./...

      - name: Set up TikZ folders
        run: go run . setup

      # Files are separated into different build steps
      # so we can track the time taken to compile each step.

      - name: Compile Numbers and Sets
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/ns/main.tex

      - name: Compile Differential Equations
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/de/main.tex

      - name: Compile Groups
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/groups/main.tex

      - name: Compile Vectors and Matrices
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/vm/main.tex

      - name: Compile Dynamics and Relativity
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/dr/main.tex

      - name: Compile Probability
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/probability/main.tex

      - name: Compile Vector Calculus
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/vc/main.tex

      - name: Compile Analysis
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ia/analysis/main.tex

      - name: Compile Optimisation
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/opt/main.tex

      - name: Compile Variational Principles
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/vp/main.tex

      - name: Compile Markov Chains
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/markov/main.tex

      - name: Compile Analysis and Topology
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/antop/main.tex

      - name: Compile Methods
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/methods/main.tex

      - name: Compile Quantum Mechanics
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/quantum/main.tex

      - name: Compile Linear Algebra
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: ib/linalg/main.tex

      - name: Compile book
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: book.tex

      - name: Optimise PDFs
        run: go run . optimise

      - name: Upload PDFs
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --prune-empty-dirs --include="*/" --include="*.pdf" --exclude="*"
          path: "."
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: thirdsgames.co.uk
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
