name: Compile LaTeX

on: push

jobs:
  compile-latex:
    name: Compile LaTeX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up GhostScript optimiser
        run: sudo apt-get install ghostscript

      - name: Get Go dependencies
        run: go get ./...

      - name: Set up TikZ folders
        run: go run . setup

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd -output-directory=build
          root_file: |
            ia/ns/main.tex
            ia/de/main.tex
            ia/groups/main.tex
            ia/vm/main.tex
            ia/dr/main.tex
            ia/probability/main.tex
            ia/vc/main.tex
            ia/analysis/main.tex
            book.tex

      - name: Optimise PDFs
        run: go run . optimise

      - name: Upload PDFs
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --prune-empty-dirs --include="*/" --include="*.pdf" --exclude="*"
          path: "."
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: thirdsgames.co.uk
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
