name: Compile LaTeX

on: push

jobs:
  compile-latex:
    name: Compile LaTeX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Set up GhostScript optimiser
        run: sudo apt-get install ghostscript

      - name: Combine into book
        run: python3 book.py

      - name: Set up TikZ folders
        run: |
          mkdir     ia/tikz book/tikz
          chmod 777 ia/tikz book/tikz

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd
          root_file: |
            ia/ns.tex
            ia/de.tex
            ia/groups.tex
            ia/vm.tex
            ia/dr.tex
            ia/probability.tex
            ia/vc.tex
            ia/analysis.tex
            book/book.tex

      - name: Optimise PDFs
        run: python3 optpdf.py

      - name: Upload PDFs
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --prune-empty-dirs --include="*/" --include="*.pdf" --exclude="*"
          path: "."
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: thirdsgames.co.uk
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
